environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"

cache:
 - "%LOCALAPPDATA%\\Yarn"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn

test_script:
  - yarn test

build: off
