language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - yarn test

notifications:
  email: false
