// flow-typed signature: cbdfaca958dea2e60e2fa082007c9d7e
// flow-typed version: <<STUB>>/co-prompt_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'co-prompt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'co-prompt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'co-prompt/examples/confirm' {
  declare module.exports: any;
}

declare module 'co-prompt/examples/password' {
  declare module.exports: any;
}

declare module 'co-prompt/examples/prompt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'co-prompt/examples/confirm.js' {
  declare module.exports: $Exports<'co-prompt/examples/confirm'>;
}
declare module 'co-prompt/examples/password.js' {
  declare module.exports: $Exports<'co-prompt/examples/password'>;
}
declare module 'co-prompt/examples/prompt.js' {
  declare module.exports: $Exports<'co-prompt/examples/prompt'>;
}
declare module 'co-prompt/index' {
  declare module.exports: $Exports<'co-prompt'>;
}
declare module 'co-prompt/index.js' {
  declare module.exports: $Exports<'co-prompt'>;
}
