// flow-typed signature: 689cd7c976a025845bd31ded1591710c
// flow-typed version: <<STUB>>/get-env-var_v^2.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-env-var'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-env-var' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'get-env-var/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'get-env-var/index' {
  declare module.exports: $Exports<'get-env-var'>;
}
declare module 'get-env-var/index.js' {
  declare module.exports: $Exports<'get-env-var'>;
}
declare module 'get-env-var/test.js' {
  declare module.exports: $Exports<'get-env-var/test'>;
}
