// flow-typed signature: 81916b513dfe127081e5831fc758801a
// flow-typed version: <<STUB>>/remove_v^0.1.5/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remove/remove' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remove/index' {
  declare module.exports: $Exports<'remove'>;
}
declare module 'remove/index.js' {
  declare module.exports: $Exports<'remove'>;
}
declare module 'remove/remove.js' {
  declare module.exports: $Exports<'remove/remove'>;
}
